# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Billy Schoelman
email: bschoelman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a civil engineer with a passion for the outdoors and adventure. I graduated from Texas A&M in 2013 and worked at Oceaneering
  till 2017. I am currently looking to leave the oil and gas field and explore my options in new rising idustries.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.BillySchoelman.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
